name: "Increment Version"

on:
  push:
  workflow_dispatch:

jobs:

  create-release-branch:
    name: "Create Release Branch"
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mparticle-automation
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-automation
      GIT_COMMITTER_EMAIL: developers@mparticle.com
    steps:
      - name: "Checkout development branch"
        uses: actions/checkout@v2
        with:
          repository: mchuangatmp/mparticle-android-sdk
          ref: main
#          submodules: recursive
      - name: "Create and push release branch"
        run: |
          git checkout -b release/${{ github.run_number }}
          git push origin release/${{ github.run_number }}
      - name: "Commit Kit Updates"
        run: |
          git submodule foreach "git fetch; git reset --hard origin/main";
          git add .
          git diff-index --quiet HEAD || git commit -m 'chore: Update Submodules'
      - name: "Push kit updates to release branch"
        run: git push origin release/${{ github.run_number }}

  semantic-release:
    name: "Semantic Release"
    needs: create-release-branch
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mparticle-automation
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-automation
      GIT_COMMITTER_EMAIL: developers@mparticle.com
    steps:
      - name: "Checkout public main branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
#      - name: "Import GPG Key"
#        uses: crazy-max/ghaction-import-gpg@v4
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#          passphrase: ${{ secrets.GPG_PASSPHRASE }}
#          git_user_signingkey: true
#          git_commit_gpgsign: true
      - name: "Merge release branch into main branch"
        run: |
          git pull origin release/${{ github.run_number }}
      - name: "Curl release.config.js"
        run: |
          curl "https://raw.githubusercontent.com/mParticle/mparticle-workflows/feat/SQDSDKS-4347/android/release.config.pr.js" > release.config.js || exit 1
      - name: "Semantic Release"
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          -p conventional-changelog-conventionalcommits \
          semantic-release
      - name: "Push automated release commits to release branch"
        run: |
          git log
          git push origin HEAD:release/${{ github.run_number }}
