name: Build and test
on: pull_request
jobs:
  instrumented-tests:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :android-core:cAT :android-kit-base:cAT --stacktrace
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results
          path: android-core/build/reports/androidTests/connected/**
  unit-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

  automerge:
      name: Rebase dependabot PRs
      runs-on: [ubuntu-latest]
      needs: [instrumented-tests, unit-tests]
      if: contains(github.repository, 'internal') && github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
      steps:
          - name: Rebase Dependabot PR
            uses: actions/github-script@v3
            with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.pulls.merge({
                        owner: context.repo.owner,
                        repo: context.payload.repository.name,
                        pull_number: context.payload.pull_request.number,
                        merge_method: 'rebase'
                    });
