name: Release SDK

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Do a dry run to preview instead of a real release [true/false]'
        required: true
        default: 'true'

jobs:
  semantic-release-job:
    runs-on: macos-latest
    env:
      GIT_AUTHOR_NAME: mparticle-bot
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-bot
      GIT_COMMITTER_EMAIL: developers@mparticle.com
    steps:
      - name: "Checkout internal/development"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: mchuangatmp/mparticle-android-sdk-internal
          token: ${{ secrets.ANDROID_SDK_PAT }}
          ref: ci/semantic_release

      # checking out the Kit submodules currently requires converting the ssh urls to https so
      # we can use the personal access tokens
      #        - name: "Checkout submodules"
      #          run: |
      #              git config --file .gitmodules --get-regexp url | while read url; do
      #              git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.SSH_KEY }}:${{ secrets.SSH_KEY }}@github.com\//")
      #            done
      #            git submodule sync
      #            git submodule update --init
#      - name: "Build and Test"
#        # build and test core, then build and test kits
#        run: |
#          ./gradlew -Ptarget_maven_repo=test -PisRelease=true cleanBuildCache clean testRelease uploadArchives
#          ./gradlew -Ptarget_maven_repo=test -PisRelease=true cleanBuildCache clean testRelease uploadArchives -c settings-kits.gradle
      - name: "Semantic Release --dry-run"
        if: ${{ github.event.inputs.dryRun == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_SDK_PAT }}
          GIT_AUTHOR_NAME: mparticle-bot
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-bot
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run
      - name: "Semantic Release"
        if: ${{ github.event.inputs.dryRun == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_SDK_PAT }}
          GIT_AUTHOR_NAME: mparticle-bot
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-bot
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release
#        - name: Merge release commits to internal master and internal development
#          run: |
#              git push origin HEAD:master

#  - name: Publish to Maven
#    if: ${{ github.event.inputs.dryRun == 'false'}}
#    env:
#      MAVEN_KEY: ${{ secrets.MAVEN_KEY }}
#      MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
#      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#      SIGNING_KEY_RING_FILE: ${{ secrets.SIGNING_KEY_RING_FILE }}
#      SIGNING_KEY_RING_PASSWORD: ${{ secrets.SIGNING_KEY_RING_PASSWORD }}
#      GIT_AUTHOR_NAME: amplitude-sdk-bot
#      GIT_AUTHOR_EMAIL: amplitude-sdk-bot@users.noreply.github.com
#      GIT_COMMITTER_NAME: amplitude-sdk-bot
#      GIT_COMMITTER_EMAIL: amplitude-sdk-bot@users.noreply.github.com
#    run: |
#     # publish code