name: "Release SDK"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Do a dry run to preview instead of a real release [true/false]'
        required: true
        default: 'true'

jobs:

  semantic-release:
    runs-on: macos-10.15
    env:
      GITHUB_TOKEN: ${{ secrets.ANDROID_SDK_PAT }}
      GIT_AUTHOR_NAME: mparticle-bot
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-bot
      GIT_COMMITTER_EMAIL: developers@mparticle.com
    steps:
      - name: "Checkout public/master Branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          token: ${{ secrets.ANDROID_SDK_PAT }}
          ref: development
      - name: "Semantic Release --dry-run"
        if: ${{ github.event.inputs.dryRun == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_SDK_PAT }}
          GIT_AUTHOR_NAME: mparticle-bot
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-bot
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run
      - name: "Semantic Release"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_SDK_PAT }}
          GIT_AUTHOR_NAME: mparticle-bot
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-bot
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release
      - name: "Merge back release commits to release branch"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git push origin HEAD:development
