name: "Release SDK"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry run to preview instead of a real release [true/false]"
        required: true
        default: "false"

jobs:

  create-release-branch:
    name: "Create Release Branch"
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.MC_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mchuangatmp
      GIT_AUTHOR_EMAIL: mchuang@mparticle.com
      GIT_COMMITTER_NAME: mchuangatmp
      GIT_COMMITTER_EMAIL: mchuang@mparticle.com
    steps:
      - name: "Checkout development branch"
        uses: actions/checkout@v2
        with:
          repository: mchuangatmp/mparticle-android-sdk
          ref: main
      - name: "Import GPG Key"
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: "Create and push release branch"
        run: |
          git checkout -b release/${{ github.run_number }}
          echo "test file" >> testfile
          git add .
          git commit -m "fix: test commit"
          git push origin release/${{ github.run_number }}
  semantic-release:
    name: "Semantic Release"
    needs: create-release-branch
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MC_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mchuangatmp
      GIT_AUTHOR_EMAIL: mchuang@mparticle.com
      GIT_COMMITTER_NAME: mchuangatmp
      GIT_COMMITTER_EMAIL: mchuang@mparticle.com
    steps:
      - name: "Checkout public main branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: "Import GPG Key"
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: "Merge release branch into main branch"
        run: |
          git pull origin release/${{ github.run_number }}
      - name: "Semantic Release --dry-run"
        if: ${{ github.event.inputs.dryRun == 'true' }}
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run
      - name: "Semantic Release"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release
      - name: "Push automated release commits to release branch"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git push origin HEAD:release/${{ github.run_number }}